name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: skill-swap

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests with Coverage
        run: npm test -- --coverage --passWithNoTests

      - name: Install SonarScanner
        run: npm install -g sonarqube-scanner

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=SRN \
            -Dsonar.organization=italotrt \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.language=ts \
            -Dsonar.sources=src \
            -Dsonar.exclusions=**/node_modules/**,**/*.test.ts \
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info